name: Build and Deploy to Docker Hub

# Trigger the workflow when a pull request is merged into the release branch
on:
  push:
    branches:
      - release  # Only trigger when code is pushed (merged) into the release branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./SimpleExpenseTracker/Server
        push: true
        tags: linkzy/simple-expense-tracker:latest
